name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, repositories
          
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_padding: 0, 8 + 2%
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, makefile, roff, xml, json, yaml, toml, npm%20config, starlark, rtf, rich%20text%20format, svg, ini, csv, pip%20requirements                
          plugin_languages_details: percentage              # Additionally display total bytes size and percentage
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used          # Display most used and recently used languages stats
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7            
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          commits_authoring: wuc9521@gmail.com  
          repositories_affiliations: owner, collaborator
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          config_timezone: America/Chicago # Set timezone
            
